name: Cypress Tests

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-16.04

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: npm run build --if-present      
    - name: Cypress.io
      uses: cypress-io/github-action@v1.16.1
      with:
          browser: chrome
          headless: true
